# Generated by Django 6.0.7 on 2026-07-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INSPECTION", "Inspection"),
                            ("MILEAGE", "Mileage Update"),
                            ("OWNERSHIP", "Ownership Change"),
                            ("SERVICE", "Service"),
                            ("ACCIDENT", "Accident"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
    ]
