# Generated by Django 6.0.7 on 2026-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicleevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="engine_capacity",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
