# Generated by Django 6.0.7 on 2026-08-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_vehicle_body_type_vehicle_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnershipRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_number", models.PositiveIntegerField()),
                ("acquired_date", models.DateField()),
                ("transferred_date", models.DateField(blank=True, null=True)),
                ("is_current_owner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_records",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-acquired_date"],
            },
        ),
    ]
