# Generated by Django 6.0.7 on 2026-08-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_ownershiprecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownershiprecord",
            name="owner_number",
        ),
        migrations.AddField(
            model_name="ownershiprecord",
            name="owner_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
