# Generated by Django 6.0.7 on 2026-08-07 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_remove_ownershiprecord_owner_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("result", models.CharField(max_length=20)),
                ("mileage", models.PositiveIntegerField()),
                ("inspection_center", models.CharField(max_length=255)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date"],
            },
        ),
    ]
