# Generated by Django 6.0.7 on 2026-08-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_inspectionrecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ownershiprecord",
            old_name="owner_name",
            new_name="owner",
        ),
    ]
